/*
 * This source file was generated by the Gradle 'init' task
 */
package sim1_eval1;

public class App {
    
    public static void main(String[] args) {
       try {
           
       } 
       
       catch (Exception e) {
            System.out.println("Ocurrió un error \n" + e);
       }
    }

    /* 
     * A los contribuyentes que tienen carro en un país les cobran 2 impuestos: el de rodamiento y el del seguro. 
     * Las tasas son seleccionadas por la década del año del modelo del auto con la tabla a continuación. 
     * 
     * Década	Tasa Rodamiento	    Tasa Seguro
        1970	      3.76%	            0,876%
        1980	      3,98%	            0,854%
        1990	      4,09%	            0,816%
        2000	      4,34%	            0,798%
        2010	      4,93%	            0,712%
        2020	      5,68%	            0,699%
        Otra	        6%	            0,9%

    Para calcular el valor a pagar por impuesto de rodamiento se debe multiplicar el valor del avaluo del 
    vehículo por la tasa de rodamiento. De igual forma se hace con el seguro pero multiplicando el avalúo
    por la respectiva tasa de seguro.

     Construya un algoritmo e implemente la función Calcular_rod_seg en Java, que reciba un short el 
     modelo (que debe estar entre 1930 y 2025) y un long con valor avalúo del vehículo 
     (que debe ser mayor o igual a 5millones), y devuelva un el valor total que el usuario deberá 
     pagar por los dos impuestos en un double. 

     Si los datos de modelo y avalúo no son váñlidos, retorne -1. 
     Si hay un error inesperado, deberá devolver 0.
    
     */



}
